### ISSUE TITLE
Personalroles - Suggestion

### ISSUE THREAD

**Issue by Ibotmealot** [brandons209/Script-Generator-Cog#19]
For tier 2 boosted guilds, Discord has added role icons. It would be cool and useful if there was an icon argument in the myrole command that lets users edit their role icon.

They must give a server emote or a default one, if not it errors. If the server doesn’t have the ability to use role icons, it also errors.

**Comment by brandons209** [comment]
Yes this would be a great feature, one I would implement if the library supported it. Unfortunately, due to how discord has been tone-deaf with the bot developer community, the create and maintainer of the discord.py api library the Red runs on is no longer updating it. So new features like threads and role icons have no support for me to add a feature like this. I am hoping the team at Redbot take up the mantle for maintaining it, but until then I don't have the time to update the library itself with those features. As soon as its available I will add this feature.

**Comment by Ibotmealot** [comment]
> Yes this would be a great feature, one I would implement if the library supported it. Unfortunately, due to how discord has been tone-deaf with the bot developer community, the create and maintainer of the discord.py api library the Red runs on is no longer updating it. So new features like threads and role icons have no support for me to add a feature like this. I am hoping the team at Redbot take up the mantle for maintaining it, but until then I don't have the time to update the library itself with those features. As soon as its available I will add this feature.

Does d.py allow you to access the Discord API manually, I know discord.js does. If d.py does, would it be possible to access it manually for the editing role icons part.

**Comment by brandons209** [comment]
Yes it does. It's something I can look into but I never messed with the API directly like that. If I get some time ill check it out.

**Comment by Ibotmealot** [comment]
Heyo, seems like fixator had actually figured it out some time ago [here](https://github.com/fixator10/Fixator10-Cogs/commit/743977be81dcce64785d220af196480e1fa8f19b#diff-1fa5abca52ca566ffec9e1c1e751d965404b7b0193a9875d2934885172e87355)

**Comment by brandons209** [comment]
Oh cool, I'll check that out.

**Comment by brandons209** [comment]
Also, since I have a template for using the API here I'll probably implement some other features with threads too. Just need to set some time aside to get it done, work has been kicking my behind.

**Comment by brandons209** [comment]
Alright, no excuses for waiting 2 weeks to do it, but I added it in. Let me know if there are any bugs, I was able to test it on my server with no issues.
