### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by Chriskm2001** [brandons209/Script-Generator-Cog#25]
The timezone is UTC but I want it as EST as the birthday cog announces the birthday before their actual birthday 

But how do I do that

**Comment by brandons209** [comment]
Well the only way to do this is to have people set their timezone with their birthday so it announces at the right time for them. I didn't add that since it made adding the birthday more of a hassal and I thought it was cleaner to announce all birthdays at the same time. 

If everyone in your server is in EST you can simply convert the timezone the user inputs to EST before saving instead of UTC as it is now. If you're needing something like I described aboved I'll look into adding that feature but it isn't high priority ATM.
