### ISSUE TITLE
Personal Roles

### ISSUE THREAD

**Issue by ooTruffle** [brandons209/Script-Generator-Cog#26]
When a user leaves a server with a set auto role created the user does not get removed from the config / roles get deleted
see [Image](https://cdn.discordapp.com/attachments/993979089419501689/1016125845846380564/unknown.png)

its noted that the offical cog does this

any way this could be fixed?

**Comment by brandons209** [comment]
Sorry for never responding to this issue, I'll take a look at this.

**Comment by brandons209** [comment]
So the cog is setup to only remove roles made by the user using autorole feature. The official cog as far as I can see does not remove the personal role from the server at all, it actually will re-add personal roles if that user rejoins, since it's all manual.

So if you set a personal role to someone manually it won't be removed automatically, it's only removed automatically if the user leaves the server and they created the role themselves using the automatic role creation feature.

**Comment by brandons209** [comment]
Closing due to no response, reopen if you still need help!
