### ISSUE TITLE
Disable

### ISSUE THREAD

**Issue by Chriskm2001** [brandons209/Script-Generator-Cog#27]
Is there a way to just disable the help command as the birthday commands and roleplay commands get disabled

**Comment by brandons209** [comment]
Hmm, not sure what you are asking, are you asking to disable the help command but not the birthday and roleplay commands? If thats so you can use permissions cog thats built in for that.

**Comment by Chriskm2001** [comment]
When I try use the permissions command it just says this

**Comment by Chriskm2001** [comment]
![Screenshot_20220919-064101~2](https://user-images.githubusercontent.com/112778174/190951041-f64e3b17-a9d2-4606-b706-46db7aa460dc.png)
![Screenshot_20220919-064042](https://user-images.githubusercontent.com/112778174/190951048-c3ab58b9-9979-4091-a68f-8403dd04e4d2.png)

**Comment by brandons209** [comment]
I'm still a little unclear on what you are asking. It seems like you are asking to just disable the help command, which I would suggest not using my cog for. I haven't tried it, but you should be able to set permissions for the help command using the permissions cog instead of the Disable cog. Something like `!permissions addserverrule deny help`

**Comment by brandons209** [comment]
Any update on this problem?

**Comment by brandons209** [comment]
Closing due to no response, reopen if you still need help!
